### ISSUE TITLE
Typescript types are incompatible with example preference center docs

### ISSUE THREAD

**Issue by MisterJimson** [knocklabs/javascript#153]
The docs here explain how to build a preference center with example code: https://docs.knock.app/in-app-ui/react/preferences#completed-preference-center

If you put this code into any typescript project you will see it littered with type errors. This is ignoring the client setup at the stop and adding type annotations to the javascript.

Example:
This section is incompatible as WorkflowPreferenceSetting can be a bool or an object.
```ts
    // from docs
    
    //Here we'll make updates to the preference set based on the preferenceType
    // and override existing channelTypeSettings
    if (preferenceType === 'category') {
      preferenceUpdate.categories[preferenceKey].channel_types =
        channelTypeSettings;
    }
    if (preferenceType === 'workflow') {
      preferenceUpdate.workflows[preferenceKey].channel_types =
        channelTypeSettings;
    }
```

```ts
// from types
    
export type WorkflowPreferenceSetting =
  | boolean
  | { channel_types: ChannelTypePreferences };
```

This results in `Property 'channel_types' does not exist on type 'false'`

There are a couple other examples if you simple try to follow the docs in a Typescript project. 

As an aside, I'm surprised there isn't a pre-built preference center like in [Novu](https://docs.novu.co/inbox/react/preference).

**Comment by JEverhart383** [comment]
Thanks for the feedback here @MisterJimson, we updated that section of the docs to better accommodate the `WorkflowPreferenceSetting` type in a better way and crosslinked a full TS example we created in another project. We've also heard the feedback about a pre-built preference center component and have that on our roadmap. I added your feedback to the product brief we have open for that component. Thanks for the suggestions and checking out Knock

**Comment by solojungle** [comment]
I'm having an issue with the code provided during build time. Does not show up with linter.
```
Type error: Object is possibly 'undefined'.

  144 | 			typeof preferenceUpdate.categories[preferenceKey] === "object"
  145 | 		) {
> 146 | 			preferenceUpdate.categories[preferenceKey].channel_types =
      | 			^
  147 | 				channelTypeSettings;
  148 | 		}
  149 | 		if (
```
