### ISSUE TITLE
Update to react-native 0.74

### ISSUE THREAD

**Issue by novemberkilo** [knocklabs/javascript#169]
I cannot install `@knocklabs/react-native` in my project because the current release of this package requires version `0.73` of react-native. Any project created with the latest version of expo will run into the same issue because latest expo brings in react-native `0.74`

I notice that in this WIP PR https://github.com/knocklabs/javascript/pull/168 the project is updated to react-native `0.74.` Any chance we could please get a release that brings these changes forward so that those of us using RN `0.74` can install the library? Thanks

**Comment by novemberkilo** [comment]
See also https://knockcustomers.slack.com/archives/C0334KQDJLF/p1722473196574669

**Comment by matgar26** [comment]
@novemberkilo Thank you for bringing this to our attention. I will get a new build pushed out tonight with the updated version requirements

**Comment by matgar26** [comment]
@novemberkilo Can you try out version 0.2.10 and let me know if that has fixed your issue?

**Comment by novemberkilo** [comment]
Thanks @matgar26 I can confirm that `npm install @knocklabs/react-native` completes cleanly now. Thanks for the quick turnaround 👍🏾

**Comment by novemberkilo** [comment]
Separately, I'm excited to use the components that will come from #168 -- thanks for your work on that :)
