### ISSUE TITLE
The bundle size.

### ISSUE THREAD

**Issue by Kevnz** [knocklabs/javascript#18]
We are a new customer to Knock have noticed that the bundle size is rather large. As listed on bundlephobia the size is listed as 740k, and 84% of that is in date-fns. This feels very heavy. Are you looking at removing that anytime soon or is bundle size not an important requirement?

**Comment by connorlindsey** [comment]
Hey @Kevnz and @ztsmith, thanks for calling out this issue and your suggestions. We've updated the package to use `Intl` for relative timestamp formatting which greatly reduced the bundle size. Upgrade to `@knocklabs/react@0.1.5` for those changes
![Screenshot 2024-02-05 at 10 19 10 AM](https://github.com/knocklabs/javascript/assets/12838032/b64a11d3-324d-474d-907f-95e337fa6074)
