### ISSUE TITLE
Knock stops receiving notifications if JWT changes

### ISSUE THREAD

**Issue by Diggsey** [knocklabs/javascript#23]
When using authentication, if the JWT provided to `<KnockFeedProvider>` changes, then notifications stop being received in the inner `<NotificationFeedPopover>`.

This occurs only in chrome, and seems to be related to the WebSocket connection being closed.

**Comment by connorlindsey** [comment]
Hi @Diggsey, we just released a new version of our JS client and React components which resolves this issue. Please upgrade to the latest versions (https://www.npmjs.com/package/@knocklabs/react/v/0.1.8) and let us know if you see any other issues. Thanks!
