### ISSUE TITLE
Unexpected CSS shift with migration

### ISSUE THREAD

**Issue by jtferns** [knocklabs/javascript#61]
When trying to migrate from `@knocklabs/react-notification-feed v0.8.11` to `@knocklabs/react v0.1.6`, following [the migration guide](https://docs.knock.app/in-app-ui/react/migrating-from-react-notification-feed), we ran into an odd CSS / styling shift. 

- before, on `@knocklabs/react-notification-feed v0.8.11`
  - ![Screenshot 2024-02-15 at 10 48 45 AM](https://github.com/knocklabs/javascript/assets/456952/7c6fba67-052b-4e4f-97bf-106cceeb4883)
- after, on `@knocklabs/react v0.1.6`
  - ![Screenshot 2024-02-15 at 10 55 53 AM](https://github.com/knocklabs/javascript/assets/456952/36284dcf-3567-4603-911c-9c41588adc19)

1️⃣ Did anything change in how the default theming applied for the Notification feed component / internals?
2️⃣ What would be required to restore the in-feed notif relative timestamp text (e.g., `10 months ago`)?

**Comment by connorlindsey** [comment]
For styling, could you confirm two things from the migration guide were completed? 
1. The CSS import should be updated to import styles from the new package `import "@knocklabs/react/dist/index.css";
`
2. If you're not using the headless mode, you should wrap your feed in the `<NotificationFeedContainer />`

For the timestamp, we recently updated how we do relative timestamp formatting to use the built in `Intl` module with the goal of reducing the package bundle size. This should work the exact same but looks like there might be an issue. What browser/OS are you seeing this in and do you see the issue in other browsers? Also, are you setting the locale when create the knock providers?

**Comment by jtferns** [comment]
1️⃣ Confirmed, the CSS import was updated as part of the migration
```tsx
- import '@knocklabs/react-notification-feed/dist/index.css';
+ import '@knocklabs/react/dist/index.css';
```

2️⃣ Ah, I'm not sure about headless mode, but our feed usage is almost identical to the [example in the docs](https://docs.knock.app/in-app-ui/react/feed#rendering-a-notification-feed) (with the only differences being the token/user information wiring).

For the timestamp, I was testing the dependency upgrade on Chrome 121/Mac 13.4; did not get a chance to confirm on Safari/Firefox, but can test those if needed. We are only passing `apiKey`, `userId`, and `userToken` to the Knock provider; should we also supply a locale there?

**Comment by connorlindsey** [comment]
@jtferns The feed container component ensures that our components have the right CSS scoping, so I'd make sure to add that: https://docs.knock.app/in-app-ui/react/migrating-from-react-notification-feed#rootless-removed-and-notificationfeedcontainer-added

**Comment by jtferns** [comment]
🙇 Thanks @connorlindsey ! I'm not sure how I missed that in migration guide, but replacing the fragment with the feed container component fixed 1️⃣ the theming issues and 2️⃣ timestamp formatting:

![Screenshot 2024-02-22 at 2 03 42 PM](https://github.com/knocklabs/javascript/assets/456952/a9dba04b-2c83-409c-b316-6dee14339131)

**Comment by connorlindsey** [comment]
@jtferns Awesome, glad that worked! Will see if we can make the migration guide clearer.

**Comment by debsouryadatta** [comment]
Thanks, I was wondering out why the styles were not visible after installation.
Adding the lin "import '@knocklabs/react/dist/index.css';"  did the work for me.
