### ISSUE TITLE
Bugs and UI improvements

### ISSUE THREAD

**Issue by stoplion** [knocklabs/javascript#95]
I know this is probably not the correct place to add this, but this will have to do bc I can't find the proper place to give you feedback

There are several frustrating UI related bugs / UX issues in your app. Here are a few:

When I'm in a 'workflow run screen' when I click this 
<img width="334" alt="CleanShot 2024-03-11 at 13 32 25@2x" src="https://github.com/knocklabs/javascript/assets/231343/77dd17c8-9bc0-4042-9caf-e615df10a609">
and get a model..
<img width="1193" alt="CleanShot 2024-03-11 at 13 31 49@2x" src="https://github.com/knocklabs/javascript/assets/231343/07b09891-a2cf-4ca8-8f02-6d30bbea159a">

there is no way to close it. I have to refresh the entire page. The 'disabled' button never enables itself and clicking the translucent backdrop doesnt close the modal either.

Also, when I'm on a 'workflows page' how do i view the Recipient email? I see it in the 'Recipient' column, but often that email is truncated. And then I would think if you clicked on that 'workflow run' I would see the Recipient email. But no, there is Recipient email in the details page. 
<img width="362" alt="CleanShot 2024-03-11 at 13 35 15@2x" src="https://github.com/knocklabs/javascript/assets/231343/1e7b67f7-eaff-4bf6-b44a-0247ff71f82c">

**Comment by cenobitedk** [comment]
I can't help you with the bugs, but they do have a slack customers workspace, maybe it's better to post there?
https://knockcustomers.slack.com

**Comment by connorlindsey** [comment]
Hi @stoplion, thanks for reporting these issues. This repository is dedicated to our JavaScript SDKs and packages and the community Slack would be the best place for these requests. Could you post these in the community Slack? It'll be easier to keep track of and respond there. Thanks!
